services:
  - type: web
    name: quiz-platform
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: ""
      - key: APP_URL
        value: "https://quiz-platform.onrender.com" # قم بتغييره لرابطك الحقيقي
